---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "2f2cabd973a3f6276c38a6be36cf8da7e9ed37af"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    provider: "fabric8"
    project: "service-crm"
    version: "1.0.1-SNAPSHOT"
    group: "co.com.summan"
  name: "service-crm"
spec:
  ports:
  - name: "rest"
    port: 9000
    protocol: "TCP"
    targetPort: 9000
  selector:
    project: "service-crm"
    provider: "fabric8"
    group: "co.com.summan"
