---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "service-crm"
    version: "0.0.1-SNAPSHOT"
    group: "co.com.summan"
  name: "service-crm"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "service-crm"
    provider: "fabric8"
    group: "co.com.summan"
