---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
    labels:
      expose: "true"
      provider: "fabric8"
      project: "service-crm"
      version: "0.0.1-SNAPSHOT"
      group: "co.com.summan"
    name: "service-crm"
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "service-crm"
      provider: "fabric8"
      group: "co.com.summan"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
      fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=service-crm&var-version=0.0.1-SNAPSHOT"
    labels:
      provider: "fabric8"
      project: "service-crm"
      version: "0.0.1-SNAPSHOT"
      group: "co.com.summan"
    name: "service-crm"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "service-crm"
        provider: "fabric8"
        group: "co.com.summan"
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: "img/icons/camel.svg"
          fabric8.io/metrics-path: "dashboard/file/camel-routes.json/?var-project=service-crm&var-version=0.0.1-SNAPSHOT"
        labels:
          provider: "fabric8"
          project: "service-crm"
          version: "0.0.1-SNAPSHOT"
          group: "co.com.summan"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "JAVA_APP_DIR"
            value: "/deployments"
          image: "service-crm:latest"
          imagePullPolicy: "Always"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 180
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
